### ISSUE TITLE
Examples use deprecated methods

### ISSUE THREAD

**Issue by danieleades** [rust-cli/config-rs#275]
a number of examples use deprecated code.

The associated lints are either addressed or silenced in #262, but the remaining examples should be updated and the lints unsilenced in a following PR.

It's not clear to me how the builder API can be used to support the use-cases in those examples...

**Comment by firegloves** [comment]
Same here, I'm trying to figure out how to use the builder API

**Comment by M-Porter** [comment]
master != 0.11.0.

You should check the example docs in the branch for whatever version you are currently using e.g https://github.com/mehcode/config-rs/blob/0.11.0/examples

**Comment by danieleades** [comment]
> master != 0.11.0.
> 
> You should check the example docs in the branch for whatever version you are currently using e.g https://github.com/mehcode/config-rs/blob/0.11.0/examples

i'm not sure what you mean?

the examples in master use methods which are deprecated in master.

**Comment by hbprotoss** [comment]
I guess it is an unreleased feature on master

**Comment by gitmalong** [comment]
https://github.com/mehcode/config-rs/blob/master/examples/hierarchical-env/settings.rs#L49

no function or associated item named `builder` found for struct `config::Config` in the current scope
function or associated item not found in `config::Config`rustc[E0599](https://doc.rust-lang.org/error-index.html#E0599)

How would that example look like with the latest version?

**Comment by matthiasbeyer** [comment]
https://github.com/mehcode/config-rs/blob/817b37807572418f48e3d660e3931d265e32ab28/examples/hierarchical-env/src/settings.rs
