### ISSUE TITLE
Re-thinking: Config source: clap

### ISSUE THREAD

**Issue by matthiasbeyer** [rust-cli/config-rs#328]
Do we want to support clap as a source of configuration?

---

This is of lower importance. First we must decide on #323

**Comment by Xuanwo** [comment]
I built a lib [serfig](https://github.com/Xuanwo/serfig) which powered by [serde-bridge](https://github.com/Xuanwo/serde-bridge) to make it possible.

The real use-case:

```rust
pub fn load() -> Result<Self> {
    let arg_conf: Self = Config::parse();

    let mut builder: serfig::Builder<Self> = serfig::Builder::default();

    // Load from config file first.
    {
        let config_file = if !arg_conf.config_file.is_empty() {
            arg_conf.config_file.clone()
        } else if let Ok(path) = env::var("CONFIG_FILE") {
            path
        } else {
            "".to_string()
        };

        builder = builder.collect(from_file(Toml, &config_file));
    }

    // Then, load from env.
    builder = builder.collect(from_env());

    // Finally, load from args.
    builder = builder.collect(from_self(arg_conf));

    Ok(builder.build()?)
}
```

Hoping these can help `config-rs` a bit!

**Comment by dnaka91** [comment]
Native support for `clap` would be great. In [Trunk](https://github.com/thedodd/trunk), we currently have config file + env file and lastly clap as input for settings. Most of the file settings can be overriden by clap as well.

At the moment we do all this merging by hand, but `config` does pretty much the same as we do, so we might want to move to it in the near future. This would be a great convenience to have.

**Comment by Sn0rt** [comment]
I also agree with this demand, and this demand still has great prospects.

**Comment by ewoolsey** [comment]
+1 on this feature!

**Comment by epage** [comment]
Closing this in favor of #64 so we don't split the conversation any further.
